# -*- coding: utf-8 -*-
"""eda_gas_price_brazil.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10MKCj_KnM1N-7_aIHFG_8JKBK3iiCvKr
"""

import pandas as pd
import os
from getpass import getpass

df = pd.read_csv("/content/gas_price_brazil/2004-2021.tsv", sep='\t')

df.head()

"""Initial Inspection and Data Quality"""

print(df.shape)  # number of line and columns

df.info() # Verifying data types

df.isnull().sum() # null values

df.duplicated().sum()  # Detect and remove duplicate records.

"""Descriptive Statistical Analysis

"""

df.describe()

"""##EDA"""

df['DATA INICIAL']

df['DATA INICIAL'] = pd.to_datetime(df['DATA INICIAL'])
df['DATA FINAL'] = pd.to_datetime(df['DATA FINAL'])

df['ANO MES'] = df['DATA FINAL'].apply(lambda x : '{}'.format(x.year)) + df['DATA FINAL'].apply(lambda x : '-{:02d}'.format(x.month))

df['ANO MES']

df.columns

"""# filtering the dataframe only with the GASOLINA COMUM registers"""

df['PRODUTO'].value_counts()

df2 = df[df['PRODUTO'] == "GASOLINA COMUM"]

df2

"""# Average gasoline price in August 2008"""

df2[df['ANO MES'] == '2008-09']['PREÇO MÉDIO REVENDA'].mean()

"""# Average gasoline price in August 2008 in Sao Paulo

estrutura de colchetes

> [selection] [[list of columns or only one list]]
"""

df2[(df2['ANO MES'] == '2008-09') & (df2['ESTADO'] == 'SAO PAULO')]['PREÇO MÉDIO REVENDA'].mean()

"""#When did the gas price go up to 5 dollars, and in which state did that happen?"""

df2[df2['PREÇO MÁXIMO REVENDA'] > 5][['ANO MES', 'ESTADO', 'PREÇO MÉDIO REVENDA']]

"""#Average gas price at the south states in 2012

"""

df_south = df2[(df2['REGIÃO'] == 'SUL')]

df_south[df_south['DATA INICIAL'].apply(lambda x: x.year) == 2012]['PREÇO MÁXIMO REVENDA'].mean()

"""##Year-over-year percentage change in gasoline prices in the state of Rio de Janeiro"""

df_rio = df2[df2['ESTADO'] == 'RIO DE JANEIRO']

df_rio['ANO'] = df_rio['DATA INICIAL'].apply(lambda x: '{}'.format(x.year))

df_rio.groupby('ANO')['PREÇO MÉDIO REVENDA'].mean()

(df_rio_perct / df_rio_perct.shift(1) -1)*100

dfrio



df_rio[df_rio.groupby('ANO')]['PREÇO MÁXIMO REVENDA'].sum()

df_south['PREÇO MÁXIMO REVENDA'].mean()

username = "italofvaz"
os.environ["GITHUB_USER"] = username

!git config --global user.name "${GITHUB_USER}"

usermail = getpass()
os.environ["GITHUB_MAIL"] = usermail

!git config --global user.email "${GITHUB_MAIL}"

usertoken = getpass()
os.environ["GITHUB_TOKEN"] = usertoken

!git clone https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/italofvaz/gas_price_brazil.git

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/gas_price_brazil/

!git add .

!git commit -m "percent price analisys"

!git push origin main